<?php
class JConfig {
	var $offline = '0';
	var $editor = 'tinymce';
	var $list_limit = '20';
	var $helpurl = 'http://help.joomla.org';
	var $debug = '0';
	var $debug_lang = '0';
	var $sef = '1';
	var $sef_rewrite = '0';
	var $sef_suffix = '0';
	var $feed_limit = '10';
	var $feed_email = 'author';
	var $secret = 'YJR8mHIRCT1rMypV';
	var $gzip = '0';
	var $error_reporting = '-1';
	var $xmlrpc_server = '0';
	var $log_path = '/home/ehhsonen/public_html/travelinsurancerating/logs';
	var $tmp_path = '/home/ehhsonen/public_html/travelinsurancerating/tmp';
	var $live_site = '';
	var $force_ssl = '0';
	var $offset = '-5';
	var $caching = '0';
	var $cachetime = '15';
	var $cache_handler = 'file';
	var $memcache_settings = array();
	var $ftp_enable = '0';
	var $ftp_host = '127.0.0.1';
	var $ftp_port = '21';
	var $ftp_user = 'jwcook';
	var $ftp_pass = 'Skjm6ulI';
	var $ftp_root = '';
	var $dbtype = 'mysql';
	var $host = 'localhost';
	var $user = 'ehhsonen_jml03';
	var $db = 'ehhsonen_jml03';
	var $dbprefix = 'jos_';
	var $mailer = 'mail';
	var $mailfrom = 'webmaster@travelinsurancerating.org';
	var $fromname = 'Travel Insurance Rating';
	var $sendmail = '/usr/sbin/sendmail';
	var $smtpauth = '0';
	var $smtpsecure = 'none';
	var $smtpport = '26';
	var $smtpuser = 'webmaster';
	var $smtppass = 'rASsQ{gFT5}q';
	var $smtphost = 'localhost';
	var $MetaAuthor = '1';
	var $MetaTitle = '1';
	var $lifetime = '15';
	var $session_handler = 'database';
	var $password = 'PujaP3cdvG';
	var $sitename = 'Travel Insurance Rating &amp; Reviews | Compare Travel Insurance';
	var $MetaDesc = 'Travel insurance company ratings and reviews.  Instant online travel insurance quotes, comparisons, and insider buying advice from leading travel insurance experts.';
	var $MetaKeys = 'Travel Insurance Ratings, Travel Insurance Rating, Travel Insurance Rankings, Travel Insurance Company Reviews, Travel Insurance Companies,
Compare travel insurance, compare cruise insurance';
	var $offline_message = 'This site is down for maintenance. Please check back again soon.';
}
?>